export interface DetalleLadosTarimaModel {
  operacion: number;
  planta_id: number;
  orden_compra_recepcion_id: number;
  tarima_id: number,
  lado_a: string,
  lado_b: string,
  lado_c: string,
  lado_d: string,
  secuencia_a: number,
  secuencia_b: number,
  secuencia_c: number,
  secuencia_d: number,
  contenedor_a: string,
  contenedor_b: string,
  contenedor_c: string,
  contenedor_d: string,
  material_a: string,
  material_b: string,
  material_c: string,
  material_d: string,
  cantidad_may_a: number,
  cantidad_may_b: number,
  cantidad_may_c: number,
  cantidad_may_d: number,
  cantidad_men_a: number,
  cantidad_men_b: number,
  cantidad_men_c: number,
  cantidad_men_d: number,
  cantidad_a: number,
  cantidad_b: number,
  cantidad_c: number,
  cantidad_d: number
}
