export interface DetalleLadosTarimaModel {
  OPERACION: number;
  PLANTA_ID: number;
  ORDEN_COMPRA_RECEPCION_ID: number;
  TARIMA_ID: number,
  LADO_A: string,
  LADO_B: string,
  LADO_C: string,
  LADO_D: string,
  SECUENCIA_A: number,
  SECUENCIA_B: number,
  SECUENCIA_C: number,
  SECUENCIA_D: number,
  CONTENEDOR_A: string,
  CONTENEDOR_B: string,
  CONTENEDOR_C: string,
  CONTENEDOR_D: string,
  MATERIAL_A: string,
  MATERIAL_B: string,
  MATERIAL_C: string,
  MATERIAL_D: string,
  CANTIDAD_MAY_A: number,
  CANTIDAD_MAY_B: number,
  CANTIDAD_MAY_C: number,
  CANTIDAD_MAY_D: number,
  CANTIDAD_MEN_A: number,
  CANTIDAD_MEN_B: number,
  CANTIDAD_MEN_C: number,
  CANTIDAD_MEN_D: number,
  CANTIDAD_A: number,
  CANTIDAD_B: number,
  CANTIDAD_C: number,
  CANTIDAD_D: number
}
